name = "iscorecloud"
main = "src/worker.ts"
compatibility_date = "2025-10-08"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "out"
binding = "ASSETS"

[observability]
enabled = true

# D1データベースの設定
[[d1_databases]]
binding = "DB"
database_name = "i-score-db"
database_id = "eadfe6d2-e75a-4234-bf68-e19a13e59648"
migrations_dir = "drizzle"

# R2オブジェクトストレージの設定
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "iscore-images"

# 環境変数の設定
[vars]
BETTER_AUTH_URL = "https://iscorecloud.com"
NEXT_PUBLIC_API_URL = "https://iscorecloud.com"
NEXT_PUBLIC_BETTER_AUTH_URL = "https://iscorecloud.com"
LINE_CLIENT_ID = "2009221282"
GOOGLE_CLIENT_ID = "792942722187-rs65cnd38a9nkncqvo0is3uk80r6118l.apps.googleusercontent.com"
MICROSOFT_CLIENT_ID = "4469e633-6c82-4cf7-b620-338d12bf76d9"